CREATE OR REPLACE TABLE PUBLIC.SILVER_ORDERS_ENRICHED AS
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_CITY,
    c.CUSTOMER_STATE,
    c.CUSTOMER_ZIP_CODE_PREFIX,

    o.ORDER_STATUS,

    o.ORDER_PURCHASE_TIMESTAMP,
    o.ORDER_APPROVED_AT,
    o.ORDER_DELIVERED_CARRIER_DATE,
    o.ORDER_DELIVERED_CUSTOMER_DATE,
    o.ORDER_ESTIMATED_DELIVERY_DATE,

    CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_PURCHASE_DATE,
    CAST(o.ORDER_APPROVED_AT AS DATE) AS ORDER_APPROVED_DATE,
    CAST(o.ORDER_DELIVERED_CARRIER_DATE AS DATE) AS ORDER_DELIVERED_CARRIER_DATE_ONLY,
    CAST(o.ORDER_DELIVERED_CUSTOMER_DATE AS DATE) AS ORDER_DELIVERED_CUSTOMER_DATE_ONLY,
    CAST(o.ORDER_ESTIMATED_DELIVERY_DATE AS DATE) AS ORDER_ESTIMATED_DELIVERY_DATE_ONLY,

    DATEDIFF(
        day,
        o.ORDER_PURCHASE_TIMESTAMP,
        o.ORDER_DELIVERED_CUSTOMER_DATE
    ) AS DAYS_TO_DELIVER,

    DATEDIFF(
        day,
        o.ORDER_ESTIMATED_DELIVERY_DATE,
        o.ORDER_DELIVERED_CUSTOMER_DATE
    ) AS DAYS_DELAY,

    CASE
        WHEN o.ORDER_DELIVERED_CUSTOMER_DATE IS NULL THEN NULL
        WHEN o.ORDER_ESTIMATED_DELIVERY_DATE IS NULL THEN NULL
        WHEN o.ORDER_DELIVERED_CUSTOMER_DATE > o.ORDER_ESTIMATED_DELIVERY_DATE THEN 1
        ELSE 0
    END AS IS_DELIVERY_DELAYED,

    CASE
        WHEN o.ORDER_DELIVERED_CUSTOMER_DATE IS NULL THEN 'not_delivered'
        WHEN o.ORDER_DELIVERED_CUSTOMER_DATE > o.ORDER_ESTIMATED_DELIVERY_DATE THEN 'delayed'
        ELSE 'on_time'
    END AS DELIVERY_STATUS,

    CURRENT_TIMESTAMP() AS SILVER_CREATED_AT

FROM PUBLIC.BRONZE_ORDERS o

LEFT JOIN PUBLIC.BRONZE_CUSTOMERS c
    ON o.CUSTOMER_ID = c.CUSTOMER_ID;