-- ============================================================
-- Tabela: PUBLIC.GOLD_DIM_PRODUTO
-- Camada: Gold
-- Objetivo: Dimensão de produtos para análise de categorias e características
-- Origem: PUBLIC.SILVER_ORDER_ITEMS_ENRICHED
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.GOLD_DIM_PRODUTO AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRODUCT_ID) AS SK_PRODUTO,
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGHT,
    PRODUCT_DESCRIPTION_LENGHT,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM,
    CURRENT_TIMESTAMP() AS GOLD_CREATED_AT
FROM (
    SELECT DISTINCT
        PRODUCT_ID,
        PRODUCT_CATEGORY_NAME,
        PRODUCT_NAME_LENGHT,
        PRODUCT_DESCRIPTION_LENGHT,
        PRODUCT_PHOTOS_QTY,
        PRODUCT_WEIGHT_G,
        PRODUCT_LENGTH_CM,
        PRODUCT_HEIGHT_CM,
        PRODUCT_WIDTH_CM
    FROM PUBLIC.SILVER_ORDER_ITEMS_ENRICHED
    WHERE PRODUCT_ID IS NOT NULL
);