-- ============================================================
-- Tabela: PUBLIC.GOLD_DIM_TEMPO
-- Camada: Gold
-- Objetivo: Dimensão calendário para análises temporais
-- Origem: PUBLIC.SILVER_ORDERS_ENRICHED + PUBLIC.SILVER_REVIEWS_ENRICHED
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.GOLD_DIM_TEMPO AS
WITH DATAS AS (
    SELECT DISTINCT
        CAST(ORDER_PURCHASE_TIMESTAMP AS DATE) AS DATA
    FROM PUBLIC.SILVER_ORDERS_ENRICHED
    WHERE ORDER_PURCHASE_TIMESTAMP IS NOT NULL

    UNION

    SELECT DISTINCT
        CAST(ORDER_APPROVED_AT AS DATE) AS DATA
    FROM PUBLIC.SILVER_ORDERS_ENRICHED
    WHERE ORDER_APPROVED_AT IS NOT NULL

    UNION

    SELECT DISTINCT
        CAST(ORDER_DELIVERED_CUSTOMER_DATE AS DATE) AS DATA
    FROM PUBLIC.SILVER_ORDERS_ENRICHED
    WHERE ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL

    UNION

    SELECT DISTINCT
        CAST(ORDER_ESTIMATED_DELIVERY_DATE AS DATE) AS DATA
    FROM PUBLIC.SILVER_ORDERS_ENRICHED
    WHERE ORDER_ESTIMATED_DELIVERY_DATE IS NOT NULL

    UNION

    SELECT DISTINCT
        CAST(REVIEW_CREATION_DATE AS DATE) AS DATA
    FROM PUBLIC.SILVER_REVIEWS_ENRICHED
    WHERE REVIEW_CREATION_DATE IS NOT NULL
)

SELECT
    TO_NUMBER(TO_CHAR(DATA, 'YYYYMMDD')) AS SK_TEMPO,
    DATA,
    YEAR(DATA) AS ANO,
    MONTH(DATA) AS MES,
    DAY(DATA) AS DIA,
    QUARTER(DATA) AS TRIMESTRE,
    DAYOFWEEK(DATA) AS DIA_SEMANA,
    DAYNAME(DATA) AS NOME_DIA_SEMANA,
    MONTHNAME(DATA) AS NOME_MES,
    CURRENT_TIMESTAMP() AS GOLD_CREATED_AT
FROM DATAS
WHERE DATA IS NOT NULL;