-- ============================================================
-- Tabela: PUBLIC.GOLD_FATO_REVIEWS
-- Camada: Gold
-- Objetivo: Fato de avaliações dos clientes
-- Origem: PUBLIC.SILVER_REVIEWS_ENRICHED + PUBLIC.SILVER_ORDERS_ENRICHED
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.GOLD_FATO_REVIEWS AS
SELECT
    r.REVIEW_ID,
    r.ORDER_ID,

    dc.SK_CLIENTE,
    dt.SK_TEMPO AS SK_TEMPO_REVIEW,

    r.REVIEW_SCORE,
    r.REVIEW_CLASSIFICATION,
    r.IS_NEGATIVE_REVIEW,
    r.IS_POSITIVE_REVIEW,
    r.HAS_REVIEW_COMMENT,
    r.DISSATISFACTION_RISK,
    r.REVIEW_TOPIC,

    r.REVIEW_COMMENT_TITLE,
    r.REVIEW_COMMENT_MESSAGE,

    r.REVIEW_CREATION_DATE_ONLY AS DATA_CRIACAO_REVIEW,
    r.REVIEW_ANSWER_DATE_ONLY AS DATA_RESPOSTA_REVIEW,

    CURRENT_TIMESTAMP() AS GOLD_CREATED_AT

FROM PUBLIC.SILVER_REVIEWS_ENRICHED r

LEFT JOIN PUBLIC.SILVER_ORDERS_ENRICHED o
    ON r.ORDER_ID = o.ORDER_ID

LEFT JOIN PUBLIC.GOLD_DIM_CLIENTE dc
    ON o.CUSTOMER_ID = dc.CUSTOMER_ID

LEFT JOIN PUBLIC.GOLD_DIM_TEMPO dt
    ON r.REVIEW_CREATION_DATE_ONLY = dt.DATA

WHERE r.REVIEW_ID IS NOT NULL;