-- ============================================================
-- Tabela: PUBLIC.GOLD_FATO_PEDIDOS
-- Camada: Gold
-- Objetivo: Fato principal de pedidos, vendas, frete e entrega
-- Origem: PUBLIC.SILVER_ORDERS_ENRICHED + PUBLIC.SILVER_ORDER_ITEMS_ENRICHED
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.GOLD_FATO_PEDIDOS AS
WITH ITENS AS (
    SELECT
        ORDER_ID,
        PRODUCT_ID,
        SELLER_ID,
        COUNT(*) AS QUANTIDADE_ITENS,
        SUM(PRICE) AS VALOR_PRODUTOS,
        SUM(FREIGHT_VALUE) AS VALOR_FRETE,
        SUM(ITEM_TOTAL_VALUE) AS VALOR_TOTAL_PEDIDO
    FROM PUBLIC.SILVER_ORDER_ITEMS_ENRICHED
    GROUP BY
        ORDER_ID,
        PRODUCT_ID,
        SELLER_ID
)

SELECT
    o.ORDER_ID,

    dc.SK_CLIENTE,
    dp.SK_PRODUTO,
    dv.SK_VENDEDOR,
    dt.SK_TEMPO AS SK_TEMPO_COMPRA,

    o.ORDER_STATUS,
    o.DELIVERY_STATUS,

    o.ORDER_PURCHASE_DATE AS DATA_COMPRA,
    o.ORDER_APPROVED_DATE AS DATA_APROVACAO,
    o.ORDER_DELIVERED_CARRIER_DATE_ONLY AS DATA_ENVIO_TRANSPORTADORA,
    o.ORDER_DELIVERED_CUSTOMER_DATE_ONLY AS DATA_ENTREGA_CLIENTE,
    o.ORDER_ESTIMATED_DELIVERY_DATE_ONLY AS DATA_ESTIMADA_ENTREGA,

    i.QUANTIDADE_ITENS,
    i.VALOR_PRODUTOS,
    i.VALOR_FRETE,
    i.VALOR_TOTAL_PEDIDO,

    o.IS_DELIVERY_DELAYED AS FLAG_ENTREGA_ATRASADA,
    o.DAYS_TO_DELIVER AS DIAS_ATE_ENTREGA,
    o.DAYS_DELAY AS DIAS_ATRASO,

    CURRENT_TIMESTAMP() AS GOLD_CREATED_AT

FROM PUBLIC.SILVER_ORDERS_ENRICHED o

INNER JOIN ITENS i
    ON o.ORDER_ID = i.ORDER_ID

LEFT JOIN PUBLIC.GOLD_DIM_CLIENTE dc
    ON o.CUSTOMER_ID = dc.CUSTOMER_ID

LEFT JOIN PUBLIC.GOLD_DIM_PRODUTO dp
    ON i.PRODUCT_ID = dp.PRODUCT_ID

LEFT JOIN PUBLIC.GOLD_DIM_VENDEDOR dv
    ON i.SELLER_ID = dv.SELLER_ID

LEFT JOIN PUBLIC.GOLD_DIM_TEMPO dt
    ON o.ORDER_PURCHASE_DATE = dt.DATA;