-- ============================================================
-- Tabela: PUBLIC.GOLD_FATO_PAGAMENTOS
-- Camada: Gold
-- Objetivo: Fato de pagamentos dos pedidos
-- Origem: PUBLIC.SILVER_PAYMENTS_ENRICHED + PUBLIC.SILVER_ORDERS_ENRICHED
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.GOLD_FATO_PAGAMENTOS AS
SELECT
    p.ORDER_ID,
    dt.SK_TEMPO AS SK_TEMPO_COMPRA,

    p.PAYMENT_SEQUENTIAL,
    p.PAYMENT_TYPE,
    p.PAYMENT_TYPE_DESCRIPTION,
    p.PAYMENT_INSTALLMENTS,
    p.INSTALLMENT_RANGE,
    p.PAYMENT_VALUE,
    p.PAYMENT_VALUE_STATUS,

    CURRENT_TIMESTAMP() AS GOLD_CREATED_AT

FROM PUBLIC.SILVER_PAYMENTS_ENRICHED p

LEFT JOIN PUBLIC.SILVER_ORDERS_ENRICHED o
    ON p.ORDER_ID = o.ORDER_ID

LEFT JOIN PUBLIC.GOLD_DIM_TEMPO dt
    ON o.ORDER_PURCHASE_DATE = dt.DATA

WHERE p.ORDER_ID IS NOT NULL;