-- ============================================================
-- View: PUBLIC.GOLD_VW_ECOMMERCE_PERFORMANCE_COMERCIAL
-- Camada: Gold
-- Objetivo: Visão consolidada para dashboard comercial
-- Origem: PUBLIC.GOLD_FATO_PEDIDOS + dimensões
-- ============================================================

CREATE OR REPLACE VIEW PUBLIC.GOLD_VW_ECOMMERCE_PERFORMANCE_COMERCIAL AS
SELECT
    dt.DATA AS DATA_COMPRA,
    dt.ANO,
    dt.MES,
    dt.NOME_MES
    dt.TRIMESTRE,

    dc.CUSTOMER_STATE AS ESTADO_CLIENTE,
    dc.CUSTOMER_CITY AS CIDADE_CLIENTE,

    dp.PRODUCT_CATEGORY_NAME,

    dv.SELLER_STATE AS ESTADO_VENDEDOR,
    dv.SELLER_CITY AS CIDADE_VENDEDOR,

    fp.ORDER_STATUS,
    fp.DELIVERY_STATUS,

    COUNT(DISTINCT fp.ORDER_ID) AS TOTAL_PEDIDOS,
    SUM(fp.QUANTIDADE_ITENS) AS TOTAL_ITENS,
    SUM(fp.VALOR_PRODUTOS) AS FATURAMENTO_PRODUTOS,
    SUM(fp.VALOR_FRETE) AS VALOR_TOTAL_FRETE,
    SUM(fp.VALOR_TOTAL_PEDIDO) AS FATURAMENTO_TOTAL,

    AVG(fp.VALOR_TOTAL_PEDIDO) AS TICKET_MEDIO,
    AVG(fp.DIAS_ATE_ENTREGA) AS MEDIA_DIAS_ENTREGA,
    AVG(fp.DIAS_ATRASO) AS MEDIA_DIAS_ATRASO,

    SUM(fp.FLAG_ENTREGA_ATRASADA) AS TOTAL_ENTREGAS_ATRASADAS,

    SUM(fp.FLAG_ENTREGA_ATRASADA) / NULLIF(COUNT(DISTINCT fp.ORDER_ID), 0) AS PERCENTUAL_ENTREGAS_ATRASADAS

FROM PUBLIC.GOLD_FATO_PEDIDOS fp

LEFT JOIN PUBLIC.GOLD_DIM_TEMPO dt
    ON fp.SK_TEMPO_COMPRA = dt.SK_TEMPO

LEFT JOIN PUBLIC.GOLD_DIM_CLIENTE dc
    ON fp.SK_CLIENTE = dc.SK_CLIENTE

LEFT JOIN PUBLIC.GOLD_DIM_PRODUTO dp
    ON fp.SK_PRODUTO = dp.SK_PRODUTO

LEFT JOIN PUBLIC.GOLD_DIM_VENDEDOR dv
    ON fp.SK_VENDEDOR = dv.SK_VENDEDOR

GROUP BY
    dt.DATA,
    dt.ANO,
    dt.MES,
    dt.NOME_MES,
    dt.TRIMESTRE,
    dc.CUSTOMER_STATE,
    dc.CUSTOMER_CITY,
    dp.PRODUCT_CATEGORY_NAME,
    dv.SELLER_STATE,
    dv.SELLER_CITY,
    fp.ORDER_STATUS,
    fp.DELIVERY_STATUS;