-- ============================================================
-- Tabela: PUBLIC.BRONZE_PAYMENTS
-- Camada: Bronze
-- Origem: PUBLIC.TB__JIZIE8__PUBLIC__TB_ORDER_PAYMENTS
-- Objetivo: Padronizar dados de pagamento dos pedidos
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.BRONZE_PAYMENTS AS
SELECT
    ORDER_ID::VARCHAR AS ORDER_ID,
    CAST(PAYMENT_SEQUENTIAL AS NUMBER) AS PAYMENT_SEQUENTIAL,
    LOWER(TRIM(PAYMENT_TYPE::VARCHAR)) AS PAYMENT_TYPE,
    CAST(PAYMENT_INSTALLMENTS AS NUMBER) AS PAYMENT_INSTALLMENTS,
    CAST(PAYMENT_VALUE AS NUMBER(18,2)) AS PAYMENT_VALUE,

    CURRENT_TIMESTAMP() AS BRONZE_CREATED_AT
FROM PUBLIC.TB__JIZIE8__PUBLIC__TB_ORDER_PAYMENTS;