-- ============================================================
-- Tabela: PUBLIC.BRONZE_REVIEWS
-- Camada: Bronze
-- Origem: PUBLIC.TB__JIZIE8__PUBLIC__TB_ORDER_REVIEWS
-- Objetivo: Padronizar dados de avaliações dos clientes
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.BRONZE_REVIEWS AS
SELECT
    REVIEW_ID::VARCHAR AS REVIEW_ID,
    ORDER_ID::VARCHAR AS ORDER_ID,
    CAST(REVIEW_SCORE AS NUMBER) AS REVIEW_SCORE,

    REVIEW_COMMENT_TITLE::VARCHAR AS REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE::VARCHAR AS REVIEW_COMMENT_MESSAGE,

    TRY_TO_TIMESTAMP_NTZ(REVIEW_CREATION_DATE::VARCHAR) AS REVIEW_CREATION_DATE,
    TRY_TO_TIMESTAMP_NTZ(REVIEW_ANSWER_TIMESTAMP::VARCHAR) AS REVIEW_ANSWER_TIMESTAMP,

    CURRENT_TIMESTAMP() AS BRONZE_CREATED_AT
FROM PUBLIC.TB__JIZIE8__PUBLIC__TB_ORDER_REVIEWS;