-- ============================================================
-- Tabela: PUBLIC.BRONZE_PRODUCTS
-- Camada: Bronze
-- Origem: PUBLIC.RAW_PRODUCTS
-- Objetivo: Padronizar dados cadastrais dos produtos
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.BRONZE_PRODUCTS AS
SELECT
    PRODUCT_ID::VARCHAR AS PRODUCT_ID,
    LOWER(TRIM(PRODUCT_CATEGORY_NAME)) AS PRODUCT_CATEGORY_NAME,

    TRY_TO_NUMBER(PRODUCT_NAME_LENGHT) AS PRODUCT_NAME_LENGHT,
    TRY_TO_NUMBER(PRODUCT_DESCRIPTION_LENGHT) AS PRODUCT_DESCRIPTION_LENGHT,
    TRY_TO_NUMBER(PRODUCT_PHOTOS_QTY) AS PRODUCT_PHOTOS_QTY,

    TRY_TO_DECIMAL(PRODUCT_WEIGHT_G, 18, 2) AS PRODUCT_WEIGHT_G,
    TRY_TO_DECIMAL(PRODUCT_LENGTH_CM, 18, 2) AS PRODUCT_LENGTH_CM,
    TRY_TO_DECIMAL(PRODUCT_HEIGHT_CM, 18, 2) AS PRODUCT_HEIGHT_CM,
    TRY_TO_DECIMAL(PRODUCT_WIDTH_CM, 18, 2) AS PRODUCT_WIDTH_CM,

    CURRENT_TIMESTAMP() AS BRONZE_CREATED_AT
FROM PUBLIC.RAW_PRODUCTS;