-- ============================================================
-- Tabela: PUBLIC.BRONZE_ORDERS
-- Camada: Bronze
-- Origem: PUBLIC.RAW_ORDERS
-- Objetivo: Padronizar tipos e nomes da tabela de pedidos
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.BRONZE_ORDERS AS
SELECT
    ORDER_ID::VARCHAR AS ORDER_ID,
    CUSTOMER_ID::VARCHAR AS CUSTOMER_ID,
    ORDER_STATUS::VARCHAR AS ORDER_STATUS,

    TRY_TO_TIMESTAMP_NTZ(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TIMESTAMP,
    TRY_TO_TIMESTAMP_NTZ(ORDER_APPROVED_AT) AS ORDER_APPROVED_AT,
    TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_DATE,
    TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_DATE,
    TRY_TO_TIMESTAMP_NTZ(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE,

    CURRENT_TIMESTAMP() AS BRONZE_CREATED_AT
FROM PUBLIC.RAW_ORDERS;