-- ============================================================
-- Tabela: PUBLIC.BRONZE_PRODUCTS
-- Camada: Bronze
-- Origem: PUBLIC.TB__JIZIE8__PUBLIC__TB_PRODUCTS
-- Objetivo: Padronizar dados cadastrais dos produtos
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.BRONZE_PRODUCTS AS
SELECT
    PRODUCT_ID::VARCHAR AS PRODUCT_ID,
    LOWER(TRIM(PRODUCT_CATEGORY_NAME::VARCHAR)) AS PRODUCT_CATEGORY_NAME,

    CAST(PRODUCT_NAME_LENGHT AS NUMBER) AS PRODUCT_NAME_LENGHT,
    CAST(PRODUCT_DESCRIPTION_LENGHT AS NUMBER) AS PRODUCT_DESCRIPTION_LENGHT,
    CAST(PRODUCT_PHOTOS_QTY AS NUMBER) AS PRODUCT_PHOTOS_QTY,

    CAST(PRODUCT_WEIGHT_G AS NUMBER(18,2)) AS PRODUCT_WEIGHT_G,
    CAST(PRODUCT_LENGTH_CM AS NUMBER(18,2)) AS PRODUCT_LENGTH_CM,
    CAST(PRODUCT_HEIGHT_CM AS NUMBER(18,2)) AS PRODUCT_HEIGHT_CM,
    CAST(PRODUCT_WIDTH_CM AS NUMBER(18,2)) AS PRODUCT_WIDTH_CM,

    CURRENT_TIMESTAMP() AS BRONZE_CREATED_AT
FROM PUBLIC.TB__JIZIE8__PUBLIC__TB_PRODUCTS;