-- ============================================================
-- Tabela: PUBLIC.BRONZE_ORDER_ITEMS
-- Camada: Bronze
-- Origem: PUBLIC.TB__JIZIE8__PUBLIC__TB_ORDER_ITEMS
-- Objetivo: Padronizar tipos e nomes da tabela de itens dos pedidos
-- ============================================================

CREATE OR REPLACE TABLE PUBLIC.BRONZE_ORDER_ITEMS AS
SELECT
    ORDER_ID::VARCHAR AS ORDER_ID,
    ORDER_ITEM_ID::NUMBER AS ORDER_ITEM_ID,
    PRODUCT_ID::VARCHAR AS PRODUCT_ID,
    SELLER_ID::VARCHAR AS SELLER_ID,

    TRY_TO_TIMESTAMP_NTZ(SHIPPING_LIMIT_DATE::VARCHAR) AS SHIPPING_LIMIT_DATE,

    PRICE::NUMBER(18,2) AS PRICE,
    FREIGHT_VALUE::NUMBER(18,2) AS FREIGHT_VALUE,

    CURRENT_TIMESTAMP() AS BRONZE_CREATED_AT
FROM PUBLIC.TB__JIZIE8__PUBLIC__TB_ORDER_ITEMS;